### ISSUE TITLE
Message and offset consumption problem

### ISSUE THREAD

**Issue by andxr** [mostafa/xk6-kafka#15]
Hi

I am currently facing a scenario in which consuming messages presents a random behavior. Right now within the test I produce in a topic, a system takes care of processing that request and writes the result of that operation in another different topic. The problem is that sometimes I am not always able to consume the message from the response topic and the test gets stuck there. I think it is because of a problem with the reading offset. 

If I read the topic from the beginning, it always works but there are more and more messages to read which makes it take longer and longer. If I read from the end I think that is when the behavior becomes random, because the answer sometimes is present before I start consuming. Using a numerical offset is not an alternative because I don't know how many messages are in the topic.

Does this make sense, and is there any way to address this problem? I had in mind the use of a temporal offset but I don't know if that would solve the problem.

Thank you!

**Comment by mostafa** [comment]
Hey @ander26,

I had the same issue while working on the consumer, which is why I added offset on the `reader` instance and limit on the `consume` function. I think another way is to have an offset and consume one by one. My original intention was to test Kafka message production, not consumption, which is why the `reader.consume` are not as mature a feature as `writer.produce`.

**Comment by ander26** [comment]
Hey @mostafa,

Thank you very much for your reply! Okay, I share with you a code snippet to see if you can help me. 

```javascript
const producer = writer(bootstrapServers, producerTopic, auth);
const consumer = reader(bootstrapServers, consumerTopic, 0, "", 0, auth );

let message = [{value: JSON.stringify(event)}];
let error = produce(producer, message);
  
let found = false;
let messages = []; 
let counter = 0;

while (!found && counter < MAXIMUM) {
    messages = consume(consumer, 1);
    if (messages.length > 0) {
      if (JSON.parse(messages[0].value).id === id) {
        found = true;
      } else {
        messages = [];
        counter++;
      }
    } else {
      messages = [];
      counter++;
    }
 }
```

This is a simplified version of the code I am developing. In this code what I do is to produce a message in a topic, an external system is in charge of processing it and I receive the answer in a different topic. To identify the requests with the answers the messages have an unique ID. That's why by means of this loop messages are read until the concrete answer to the request is read or until a timeout occurs. Here I have played with the offsets (I have modified the original code to accept also -1 and -2), trying the following values:

- -1: To read the last offset, the problem it generates for me is that it is not able to read the message and gets stuck there. My theory is that when it establishes the offset the message is already in the topic, so at the time of consuming new messages there are no. 
- -2: It is read from the beginning so I am able to read the message but the more tests I launch the bigger the topic content is and the slower the processing.
- Manual Offset: It works well but I need to check manually each time I run the test which is the offset in which the topic goes. This way I lose automatism. 

Among my ideas to address this problem were the option to query that offset before starting to consume or make use of a temporary offset. I do not know if there is something that I am not taking into account or if there is a simpler way to address this problem.

**Comment by timkersch** [comment]
Hey,

I am trying to test a similar setup with produce / consume.
However I'm using the consumer group option instead of a partition-consumer, sometimes I do get messages for the consumer but mostly it just gets stuck and does not receive anything. 

@andxr did you find a workaround?

**Comment by mostafa** [comment]
@andxr 

I added [`startOffset`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/ReaderConfig.md#startoffset) to the `ReaderConfig` and I suppose this is resolved. Feel free to reopen it if the issue persists.
