### ISSUE TITLE
Q: Unable to read messages

### ISSUE THREAD

**Issue by MehrCurry** [mostafa/xk6-kafka#180]
I have a simple kafka setup with the strimzi operator in a kubernetes cluster. I have written a small test which produces to one topic a reads from another (where the results should be placed). Producing works just fine but reading gives me only a single error message "Unable to read messages".

Excerpt from my test
```
const brokers = ['kafka-kafka-bootstrap.kafka.svc.cluster.local:9092'];
const sendTopic = 'wmbus';
const recvTopic = 'wmbusDecoded';

const writer = new Writer({
    brokers: brokers,
    topic: sendTopic
});

const reader = new Reader({
    brokers: brokers,
    topic: recvTopic
});

const connection = new Connection({
  address: brokers[0],
});

...

export default function () {
  const count = 1000;

  ...

  let results = reader.consume({ limit: count });

  check(results, {
          "correct number of messages are received": (results) => results.length == count,
      });
}

```
Did i miss anything? Is there a way to get more meaningful error details?

**Comment by MehrCurry** [comment]
Ok, it seems that the message is a bit misleading. I got also the message that the correct number of messages is received.

Message in context:

```
DEBU[0039] running thresholds                            component=metrics-engine metric_name=kafka.reader.error.count
DEBU[0039] running thresholds                            component=metrics-engine metric_name=kafka.writer.error.count
DEBU[0041] running thresholds                            component=metrics-engine metric_name=kafka.reader.error.count
DEBU[0041] running thresholds                            component=metrics-engine metric_name=kafka.writer.error.count
ERRO[0042] Unable to read messages.                      error="Unable to read messages."
DEBU[0042] Executor finished successfully                executor=default startTime=0s type=constant-vus
DEBU[0042] Running teardown()                            phase=local-execution-scheduler-run
```

**Comment by mostafa** [comment]
Hey @MehrCurry,

When you ran the test, you probably have used many VUs and iterations to simulate the load. Thus, by the time your `recvTopic` is populated with message, the consumer was unable to read messages, because there were none, and the iteration has ended and the consumer gave up. AFAIK, this might be the cause.

Consider increasing the [`MaxWait`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/ReaderConfig.md#maxwait) in the Reader's config parameters. The default is 200 milliseconds, as set by the extension if you don't provide any value. Also take into account that increasing this value will increase iteration duration.

**Comment by MehrCurry** [comment]
Thank you for your hints. To be honest, i am not really sure whats happening.

I increased the maxWait like this:

```
const reader = new Reader({
    brokers: brokers,
    topic: recvTopic,
    maxWait: 30000,
    groupId: 'k6-consumer'
});
```
Via AKHQ i can see that the consumer is present and has consumed all availible messages (lag:0) but the `consume(...)` call does not return and timesout.

![grafik](https://user-images.githubusercontent.com/328753/203313411-ced5b1a9-4a01-4c28-81d5-d989331dd799.png)

```
go package net: using cgo DNS resolver
  execution: local
     script: test_wmbus.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 1m30s max duration (incl. graceful stop):
           * default: 1 looping VUs for 1m0s (gracefulStop: 30s)

ERRO[0093] Unable to read messages.                      error="Unable to read messages."

running (1m31.2s), 0/1 VUs, 0 complete and 1 interrupted iterations
default ✓ [======================================] 1 VUs  1m0s
WARN[0093] No script iterations finished, consider making the test duration longer
```

**Comment by mostafa** [comment]
@MehrCurry 
In the previous example you provided, there was no mention of `groupId`. If you are using `groupId` (which is actually [`groupID`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/ReaderConfig.md#groupid) - notice the uppercase `D`), you need to adjust the [`sessionTimeout`](https://github.com/mostafa/xk6-kafka/blob/main/api-docs/docs/interfaces/ReaderConfig.md#sessiontimeout) instead of `maxWait`.

**Comment by MehrCurry** [comment]
Sad thing. I added the `groupId` together with `maxWait` to identify the consumer in AKQH and to see if and when those messages where consumed. I tried with and without `maxWait` and/or `sessionTimeout`with no luck.

What i should mention: The topic has 20 partitions. How does the reader deal with multiple partitions? I thought it will listen on all partitions, but when it listens only on a single partition that might be the cause for the problems reading the expected amount of messages.

**Comment by mostafa** [comment]
@MehrCurry 
I recommend reading about [consumer groups](https://docs.confluent.io/platform/current/clients/consumer.html#consumer-groups) on the Confluent docs. Essentially, when you have a consumer group:
> The partitions of all the topics are divided among the consumers in the group.

That way, you don't have to deal with partitions anymore and the consumer should be able to retrieve messages of a topic from some/all partitions. Since xk6-kafka uses kafka-go to access Kafka, I recommend reading the comments in [this piece of the code](https://github.com/segmentio/kafka-go/blob/eba9cae7fd57401a8078f6f25bc00cb753cd4f42/reader.go#L352-L523) to figure out which options you need to populate.

**Comment by MehrCurry** [comment]
Hi @mostafa i very much appreciate your help. I know about kafka and consumer groups and kafka. What i tried to find out, is how to configure the Reader in a appropriate way.

Sadly, i stopped working with k6. The heavylifting to get things running is to much for out small PoC.

But anyway, thanks again for your help.

**Comment by mostafa** [comment]
@MehrCurry Fair enough! I'll write more docs in the future to fix this issue.

**Comment by vvasilevbosch** [comment]
@mostafa May I ask here if there is any way to configure read timeout for consumer, I tried setting maxWait, sessionTimeout(when using groupID), readBatchTimeout

**Comment by mostafa** [comment]
@vvasilevbosch Those are the fields usually used. There was an opinionated value, 200 ms, I used to set for `maxWait` to let it give up early, but that proved to be causing issues with some tests. Please try setting them to milliseconds values to see if the behavior changes. Otherwise I need to see your script.

**Comment by vvasilevbosch** [comment]
@mostafa Thanks for the quick reply. With default maxWait(200ms), the message 'Unable to read messages' is shown after 10min30s(basically the duration + graceful shutdown time). Shouldn't it fail after 200ms?

**Comment by mostafa** [comment]
@vvasilevbosch This means there's a configuration problem. Can you produce messages successfully?

**Comment by vvasilevbosch** [comment]
@mostafa Yes, I can produce and consume messages, but for testing purposes I am not sending a message, only consuming and want to handle such behaviour

**Comment by mostafa** [comment]
@vvasilevbosch If there's no message in your topic, the reader keeps hanging. That's unfortunately the current behavior. I need to fix it with some internal context timeout. I made a ticket (#196) to fix it.

**Comment by vvasilevbosch** [comment]
@mostafa Great! By the way, I just noticed that if there was initial message to read, the functionality works as expected(f.e. send 1 message, read 1, and then read one more)
