### ISSUE TITLE
Producing msgpack messages with xk6-kafka 

### ISSUE THREAD

**Issue by bmckerry** [mostafa/xk6-kafka#248]
Hello! I'm looking into load testing some kafka consumers with k6 and was able to get a basic script running which can send JSON messages to a local kafka.

However, the consumers I'm trying to test expect JSON messages received to be packed via [msgpack](https://github.com/msgpack/msgpack-javascript) before they're produced to a topic. I'm not able to find anything related to msgpack encoding in the xk6-kafka SchemaRegistry (and can't find a msgpack client in the [k6 Module docs](https://k6.io/docs/using-k6/modules/)). Apologies if I'm missing something (very new to both k6 and JS in general), but is it possible to test our consumers with xk6-kafka?

**Comment by mostafa** [comment]
@bmckerry 

Msgpack is neither supported by xk6-kafka, nor by [Schema Registry](https://github.com/confluentinc/schema-registry) AFAIK. So, I don't promise that I'll add it, yet I'd be happy to see contributions.

An alternative is to use the [msgpack JS library](https://github.com/msgpack/msgpack-javascript) and [bundle](https://k6.io/docs/using-k6/modules/#bundling-node-modules) it. Since msgpack is a binary protocol and you can send and receive [ByteArray](https://github.com/mostafa/xk6-kafka/blob/main/scripts/test_bytes.js) using xk6-kafka, you'll be able to test your platform.

**Comment by bmckerry** [comment]
Thanks for your quick response! I'll look into using the bundler, appreciate your help.
