### ISSUE TITLE
Be able to update offset of kafka reader

### ISSUE THREAD

**Issue by vvargas90** [mostafa/xk6-kafka#270]
As of today, the process of consuming messages using xk6-kafka is as follows:
1. Create Connection + a Reader with a certain offset.
2. Use the `consume` method to consume a certain amount of events

This works very well but when it comes to testing high volumes of traffic the offset gets outdated quite soon and we have to start over again by creating a new Reader with a certain offset to omit those consumed events.

It would be able to either:
- Consume events continuously.
- Update the offset without having to recreate the reader every time.

**Comment by vvargas90** [comment]
After digging into the reader options I see there's a `commitInterval` option which might be what I'm looking for, am I right?

**Comment by mostafa** [comment]
Hey @vvargas90,

The reader object is not built to test the system, since it has its own set of issues. I originally created it to do quick smoke testing to see if the messages are correctly produced. I presume that it is possibly not the Kafka instance itself you're testing, rather your consumers. Nonetheless, the [`commitInterval`](https://github.com/segmentio/kafka-go/blob/2af3101bdba0698ff97117cd2b0051510d996df7/reader.go#L427-L433) is only used if you have the `groupID` set, which means that you're using a consumer group.

**Comment by vvargas90** [comment]
I'm working on a set of performance tests that have the following setup (very simplified) where Service B is the service under test:
- Service A produces events that are consumed by service B
- Service B responds to those events with an action that has to be acknowledged by Service A and is identified with an id.
- Service A responds to that with a custom message that contains that id. 

So long story short, in the k6 test I'm designing I have to produce the events as if I'm Service A, consume the messages from Service B and then answer back as if I'm Service A. 

If as of today I need to recreate the consumer with a new offset I will go into that path, but it would be great for these use cases be able to consume continuously events as a feature 😄

**Comment by mostafa** [comment]
I understand your concern and use-case, however the reader will hang if the `limit` and `maxWait` are not defined (assigned to, actually), hence why there has been many iterations to fix this "bug" in the reader to stop consuming and give up resources, so that k6 can tear down the test. Now you want the opposite, which is interesting.

**Comment by vvargas90** [comment]
Hey @mostafa thanks for the heads up! For the record, the solution I will be using looks like 

```
  export function foo() {
    var offsetForConsumer = __ENV.OFFSET;
    var consumerBatchSize = __ENV.CONSUMER_BATCH_SIZE

    const kafkaAvroProducer = new NewKafkaAvroProducer(
      brokers,
      topic,
      { schemaRegistry: schemaRegistry, schema: schema }
    );
    while (testDuration) {
      console.log("creating new consumer with offset " + offsetForConsumer);
      const kafkaAvroConsumer = new KafkaAvroConsumer(
        brokers,
        topic,
        schemaUrl,
        schemaName,
        offsetForConsumer,
      );

      var commands = kafkaAvroDispatcherCommandsConsumer.consumeMessages(consumerBatchSize);
      var offsetForConsumer = offsetForConsumer + commands.length
      console.log("next offset will be " + offsetForConsumer);

      // Logic of the script under test

      kafkaAvroProducer.produceMessagesInBatch(events);
      kafkaAvroConsumer.close();
      sleep(5);
    }
    kafkaAvroProducer.close();
  }
```

Ultimately, I'm recreating the consumer on every while loop iteration. Even if not ideal it works.

**Comment by mostafa** [comment]
@vvargas90 

Nice work! Also, it doesn't have to be ideal, if it gets the job done.

**Comment by vvargas90** [comment]
Feel free to close the issue if you want or consider converting it into a feature, up to you!
